### ISSUE TITLE
extractTrack should not rely on onaddstream

### ISSUE THREAD

**Issue by fippo** [opentok/rtcstats-server#238]
https://github.com/opentok/rtcstats-server/blob/develop/features.js#L189-L220
relies on onaddstream. This caused a decrease in the number of records for some of our quality metrics.

Action:
1) fix this
2) shake fist at @henbos

**Comment by henbos** [comment]
Haha! This is what you get for relying on legacy APIs ;)

Also, sorry about that - it's now fixed, but do rely on ontrack instead.

**Comment by fippo** [comment]
hey, alot of the stuff in here still relies on legacy stats :-p

**Comment by henbos** [comment]
May I suggest a migration plan relying on calling both old and new getStats in parallel for a transition period? If it exists in new - use that - otherwise, fallback on filling in the reports with legacy crap.

The stats don't map 1:1 so doing a switch would realistically have to be a transition, even if there was full coverage.
